version: "3.9"
services:

  product:
    build:
      args:
        user: deployer
        uid: 1000
      context: ./services/product
      dockerfile: Dockerfile
    image: product-service
    container_name: product-service
    restart: unless-stopped
    working_dir: /var/www/product
    volumes:
      - ./services/product:/var/www/product
    networks:
      - intranet

  gateway:
    build:
      args:
        user: deployer
        uid: 1000
      context: ./services/gateway
      dockerfile: Dockerfile
    image: gateway-service
    container_name: gateway-service
    restart: unless-stopped
    working_dir: /var/www/gateway
    volumes:
      - ./services/gateway:/var/www/gateway
    networks:
      - intranet

  mysql:
    image: mysql:latest
    container_name: mysql-service
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: gateway
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: mysql_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./services/mysql/init_db:/docker-entrypoint-initdb.d
      - ./services/mysql/data:/var/lib/mysql
    networks:
      - intranet

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
     - PMA_HOST=mysql
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.docker-microservices`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=intranet"
      - "traefik.docker.network=intranet"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

  nginx:
    image: nginx:1.21.6-alpine
    container_name: nginx-service
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=intranet"
      # Define a router to direct HTTP traffic for 'gateway.docker-microservices' to the port 80 of this service
      - "traefik.http.routers.gateway.service=gateway" 
      - "traefik.http.routers.gateway.rule=Host(`gateway.docker-microservices`)"
      - "traefik.http.routers.gateway.entrypoints=intranet"
      - "traefik.http.services.gateway.loadbalancer.server.port=80"
      # Define a router to direct HTTP traffic for 'product.docker-microservices' to the port 8080 of this service 
      - "traefik.http.routers.product.service=product"
      - "traefik.http.routers.product.rule=Host(`product.docker-microservices`)"
      - "traefik.http.routers.product.entrypoints=intranet"
      - "traefik.http.services.product.loadbalancer.server.port=8080"
    volumes:
      - ./services/product:/var/www/product
      - ./services/gateway:/var/www/gateway
      - ./services/nginx:/etc/nginx/conf.d
    networks:
      - intranet


networks:
  intranet:
    external: true
